removed crazy line endings; simplified crazy greps

diff --git a/pre-commit b/pre-commit
--- a/pre-commit
+++ b/pre-commit
@@ -28,62 +28,61 @@ if [ -f "$git_root/.git" ]; then
     fi
 fi
 
-for changedfile in `git diff --cached --name-only --diff-filter=ACM`; do
-    #check puppet manifest syntax
-    if type puppet >/dev/null 2>&1; then
-        if [ $(echo $changedfile | grep -q '\.*.pp$'; echo $?) -eq 0 ]; then
-            ${subhook_root}/puppet_manifest_syntax_check.sh $changedfile
+
+#check puppet manifest syntax
+if type puppet >/dev/null 2>&1; then
+    for changedfile in `git diff --cached --name-only -- '*.pp'`; do
+      ${subhook_root}/puppet_manifest_syntax_check.sh $changedfile
+      RC=$?
+      if [ "$RC" -ne 0 ]; then
+          failures=`expr $failures + 1`
+      fi
+    done
+else
+    echo "puppet not installed. Skipping puppet syntax checks..."
+fi
+
+if type ruby >/dev/null 2>&1; then
+    #check erb (template file) syntax
+    if type erb >/dev/null 2>&1; then
+        for changedfile in `git diff --cached --name-only -- '*.erb'`; do
+            ${subhook_root}/erb_template_syntax_check.sh $changedfile
             RC=$?
             if [ "$RC" -ne 0 ]; then
                 failures=`expr $failures + 1`
             fi
-        fi
+        done
     else
-        echo "puppet not installed. Skipping puppet syntax checks..."
+        echo "erb not installed. Skipping erb template checks..."
     fi
 
-    if type ruby >/dev/null 2>&1; then
-        #check erb (template file) syntax
-        if type erb >/dev/null 2>&1; then
-            if [ $(echo $changedfile | grep -q '\.*.erb$'; echo $?) -eq 0 ]; then
-                ${subhook_root}/erb_template_syntax_check.sh $changedfile
-                RC=$?
-                if [ "$RC" -ne 0 ]; then
-                    failures=`expr $failures + 1`
-                fi
-            fi
-        else
-            echo "erb not installed. Skipping erb template checks..."
+    #check hiera data (yaml/yml) syntax
+    for changedfile in `git diff --cached --name-only -- '*.eyaml' '*.eyml' '*.yaml' '*.yml'`; do
+        ${subhook_root}/yaml_syntax_check.sh $changedfile
+        RC=$?
+        if [ "$RC" -ne 0 ]; then
+            failures=`expr $failures + 1`
         fi
+    done
+else
+    echo "ruby not installed. Skipping erb/yaml checks..."
+fi
 
-        #check hiera data (yaml/yml) syntax
-        if [ $(echo $changedfile | grep -q '\.*.yaml$\|\.*.yml$'; echo $?) -eq 0 ]; then 
-            ${subhook_root}/yaml_syntax_check.sh $changedfile
-            RC=$?
-            if [ "$RC" -ne 0 ]; then
-                failures=`expr $failures + 1`
-            fi
+#puppet manifest styleguide compliance
+if type puppet-lint >/dev/null 2>&1; then
+    for changedfile in `git diff --cached --name-only -- '*.pp'`; do
+        ${subhook_root}/puppet_lint_checks.sh $changedfile
+        RC=$?
+        if [ "$RC" -ne 0 ]; then
+            failures=`expr $failures + 1`
         fi
-    else
-        echo "ruby not installed. Skipping erb/yaml checks..."
-    fi
-
-    #puppet manifest styleguide compliance
-    if type puppet-lint >/dev/null 2>&1; then
-        if [ $(echo $changedfile | grep -q '\.*.pp$' ; echo $?) -eq 0 ]; then 
-            ${subhook_root}/puppet_lint_checks.sh $changedfile
-            RC=$?
-            if [ "$RC" -ne 0 ]; then
-                failures=`expr $failures + 1`
-            fi
-        fi
-    else
-        echo "puppet-lint not installed. Skipping puppet-lint tests..."
-    fi
-done
+    done
+else
+    echo "puppet-lint not installed. Skipping puppet-lint tests..."
+fi
 
 #rspec test validation
-if which rspec >/dev/null 2>&1; then
+if type rspec >/dev/null 2>&1; then
     ${subhook_root}/rspec_puppet_checks.sh
     RC=$?
     if [ "$RC" -ne 0 ]; then
@@ -95,7 +94,7 @@ fi
 
 #summary
 if [ "$failures" -ne 0 ]; then
-    echo -e "\e[0;31mError: $failures subhooks failed. Aborting commit.\e[0m"
+    echo -e "Error: $failures subhooks failed. Aborting commit."
     exit 1
 fi
 
diff --git a/pre-receive b/pre-receive
--- a/pre-receive
+++ b/pre-receive
@@ -38,7 +38,7 @@ while read oldrev newrev refname; do
             fi
 
             #check hiera data (yaml/yml) syntax
-            if [ $(echo $changedfile | grep -q '\.*.yaml$\|\.*.yml$'; echo $?) -eq 0 ]; then 
+            if [ $(echo $changedfile | grep -q '\.*.yaml$\|\.*.yml$'; echo $?) -eq 0 ]; then
                 ${subhook_root}/yaml_syntax_check.sh $tmpmodule "${tmptree}/"
                 RC=$?
                 if [ "$RC" -ne 0 ]; then
@@ -51,7 +51,7 @@ while read oldrev newrev refname; do
 
         #puppet manifest styleguide compliance
         if type puppet-lint >/dev/null 2>&1; then
-            if [ $(echo $changedfile | grep -q '\.*.pp$' ; echo $?) -eq 0 ]; then 
+            if [ $(echo $changedfile | grep -q '\.*.pp$' ; echo $?) -eq 0 ]; then
                 ${subhook_root}/puppet_lint_checks.sh $tmpmodule "${tmptree}/"
                 RC=$?
                 if [ "$RC" -ne 0 ]; then
@@ -67,7 +67,7 @@ rm -rf ${tmptree}
 
 #summary
 if [ "$failures" -ne 0 ]; then
-    echo -e "\e[0;31mError: $failures subhooks failed. Declining push.\e[0m"
+    echo -e "Error: $failures subhooks failed. Declining push."
     exit 1
 fi
 
